#ifndef lingua_h
#define lingua_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

namespace lingua {

struct LinguaDetector;

/// Result structure for confidence values
struct ConfidenceValue {
  char *language_code;
  double confidence;
};

extern "C" {

void set_error(const char **err, const str *error_message);

const char *get_error();

/// Creates a language detector with all languages
LinguaDetector *lingua_detector_create_all();

/// Creates a language detector with specific languages
/// languages: comma-separated ISO 639-1 codes (e.g., "en,fr,de,es")
LinguaDetector *lingua_detector_create_from_languages(const char *languages, const char **error);

/// Detects the language of the given text
/// Returns the ISO 639-1 code (e.g., "en") or null if detection failed
char *lingua_detect_language(const LinguaDetector *detector, const char *text, const char **error);

/// Computes the confidence value for a specific language
double lingua_compute_language_confidence(const LinguaDetector *detector,
                                          const char *text,
                                          const char *language_code,
                                          const char **error);

/// Computes confidence values for all languages
/// Returns an array of ConfidenceValue structs and sets the count
ConfidenceValue *lingua_compute_language_confidence_values(const LinguaDetector *detector,
                                                           const char *text,
                                                           int *count,
                                                           const char **error);

/// Frees a string allocated by lingua
void lingua_free_string(char *s);

/// Frees the confidence values array
void lingua_free_confidence_values(ConfidenceValue *values, int count);

/// Destroys the detector and frees memory
void lingua_detector_destroy(LinguaDetector *detector);

} // extern "C"

} // namespace lingua

#endif // lingua_h
